{"errorMessage":"Lambda process returned error status code: 125. Result: . Output:\ndocker: Error response from daemon: error while creating mount source path '/zipfile.c2d7cfad': mkdir /zipfile.c2d7cfad: read-only file system.","errorType":"InvocationException","stackTrace":["  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 729, in run_lambda\n    callback=callback,\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 224, in execute\n    return do_execute()\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 214, in do_execute\n    return _run(func_arn=func_arn)\n","  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 157, in wrapped\n    raise e\n","  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 153, in wrapped\n    result = func(*args, **kwargs)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 201, in _run\n    raise e\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 189, in _run\n    result = self._execute(func_arn, func_details, event, context, version)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 451, in _execute\n    cmd, event=stdin, env_vars=environment, func_details=func_details\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 342, in run_lambda_executor\n    result,\n"]}
